### ISSUE TITLE
Can't compile in Unity 2022?

### ISSUE THREAD

**Issue by Thundros** [hecomi/uDllExporter#1]
@hecomi Hi, can you please make this work with the latest version of Unity? I keep getting errors that I cannot fix...

Thank you!

**Comment by Thundros** [comment]
@hecomi hello?

**Comment by Thundros** [comment]
???

**Comment by hecomi** [comment]
As noted in the README, this editor extension does not currently work with Unity versions 2019.2 and later because the location of the DLL changes.

**Comment by Thundros** [comment]
@hecomi where are the new locations? how do i fix this? i REALLY need to be able to use this plugin.

**Comment by hecomi** [comment]
You are able to look it up yourself in the Unity directory. For example, on a Mac, please look for the following location:

- /Applications/Unity/Hub/Editor/2021.3.0f1/Unity.app/Contents/Managed, etc. 

If there are any dependent packages, they must be included as well. To automate this process requires updating a lot of code updates, so if it is urgently needed, it is recommended to create a DLL using the normal procedure rather than using this editor plugin because I have no plans to maintain this plugin at this time.

**Comment by Thundros** [comment]
@hecomi I am on windows
